---

- name: Fresh Linux Development Setup
  hosts: localhost
  roles:
#      Common Stuff
#    - { role: git, become: true, username: 'example', email: 'example@example.com' }
#    - { role: guake, become: true }
#    - { role: zsh, become: true }
#    - { role: chromium, become: true }

#      IDEs
#    - { role: phpstorm, become: true }
#    - { role: webstorm, become: true }
#    - { role: idea, become: true }
#    - { role: clion, become: true }
#    - { role: atom, become: true }

#      System
#    - { role: docker, become: true }
#    - { role: nvm, become: true }
